# start up
/run/initialize
# open an OpenGL viewer
/vis/open OGL
# draw geometry
/vis/drawVolume
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# Make the "World" box invisible
/vis/geometry/set/visibility World 0 false
